/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ExternalAffairs;

/**
 *
 * @author HP
 */
public class CampusManager extends javax.swing.JPanel {

    /**
     * Creates new form CampusManager
     */
    public CampusManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHelloCampusManager = new javax.swing.JLabel();
        ScrollPaneDormNumber = new javax.swing.JScrollPane();
        tblDormNumber = new javax.swing.JTable();
        btnSearchDorm = new javax.swing.JButton();
        txtEnterDormNo = new javax.swing.JTextField();
        lblEnterDormNo = new javax.swing.JLabel();
        SpinnerDormNumber = new javax.swing.JSpinner();
        btnAssignSpace = new javax.swing.JButton();

        lblHelloCampusManager.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        lblHelloCampusManager.setText("Hello Campus Manager !!!");

        tblDormNumber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Dorm Number", "Available Space"
            }
        ));
        ScrollPaneDormNumber.setViewportView(tblDormNumber);

        btnSearchDorm.setText("Search Dorm");

        lblEnterDormNo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblEnterDormNo.setText("Enter Dorm No :");

        btnAssignSpace.setText("Assign Space");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblHelloCampusManager)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SpinnerDormNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAssignSpace))
                            .addComponent(ScrollPaneDormNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnterDormNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEnterDormNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchDorm)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSearchDorm, txtEnterDormNo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHelloCampusManager)
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchDorm)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEnterDormNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEnterDormNo)))
                .addGap(18, 18, 18)
                .addComponent(ScrollPaneDormNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerDormNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignSpace))
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneDormNumber;
    private javax.swing.JSpinner SpinnerDormNumber;
    private javax.swing.JButton btnAssignSpace;
    private javax.swing.JButton btnSearchDorm;
    private javax.swing.JLabel lblEnterDormNo;
    private javax.swing.JLabel lblHelloCampusManager;
    private javax.swing.JTable tblDormNumber;
    private javax.swing.JTextField txtEnterDormNo;
    // End of variables declaration//GEN-END:variables
}
