/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.StudentAffairsOffice;

/**
 *
 * @author HP
 */
public class CareerCounsellor extends javax.swing.JPanel {

    /**
     * Creates new form CareerCounsellor
     */
    public CareerCounsellor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScheduleAppointmentScrollPane = new javax.swing.JScrollPane();
        ScheduleAppointmentTable = new javax.swing.JTable();
        lblScheduleAppointment = new javax.swing.JLabel();
        btnAssignItToMe = new javax.swing.JButton();
        lblCareerCounsellor = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(850, 600));

        ScheduleAppointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Student ID", "Name", "Status"
            }
        ));
        ScheduleAppointmentScrollPane.setViewportView(ScheduleAppointmentTable);

        lblScheduleAppointment.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lblScheduleAppointment.setText("Schedule Appointment");

        btnAssignItToMe.setText("Assign It To Me");

        lblCareerCounsellor.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        lblCareerCounsellor.setText("Career Counsellor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCareerCounsellor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAssignItToMe)
                        .addComponent(ScheduleAppointmentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblScheduleAppointment))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCareerCounsellor)
                .addGap(60, 60, 60)
                .addComponent(lblScheduleAppointment)
                .addGap(18, 18, 18)
                .addComponent(ScheduleAppointmentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAssignItToMe)
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScheduleAppointmentScrollPane;
    private javax.swing.JTable ScheduleAppointmentTable;
    private javax.swing.JButton btnAssignItToMe;
    private javax.swing.JLabel lblCareerCounsellor;
    private javax.swing.JLabel lblScheduleAppointment;
    // End of variables declaration//GEN-END:variables
}
