/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.StudentAffairsOffice;

/**
 *
 * @author HP
 */
public class ScheduleAppointments extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleAppointments
     */
    public ScheduleAppointments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        lblSelectDate = new javax.swing.JLabel();
        btnScheduleAppointment = new javax.swing.JButton();
        lblHelloStudent = new javax.swing.JLabel();
        lblScheduleYourAppointment = new javax.swing.JLabel();

        lblSelectDate.setText("Select Date :");

        btnScheduleAppointment.setText("Schedule Appointment");

        lblHelloStudent.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        lblHelloStudent.setText("Hello Student !!!");

        lblScheduleYourAppointment.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lblScheduleYourAppointment.setText("Schedule Your Appointment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnScheduleAppointment)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSelectDate)
                                .addGap(18, 18, 18)
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHelloStudent))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblScheduleYourAppointment)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHelloStudent)
                .addGap(18, 18, 18)
                .addComponent(lblScheduleYourAppointment)
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelectDate)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnScheduleAppointment)
                .addContainerGap(233, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnScheduleAppointment;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel lblHelloStudent;
    private javax.swing.JLabel lblScheduleYourAppointment;
    private javax.swing.JLabel lblSelectDate;
    // End of variables declaration//GEN-END:variables
}
